### ISSUE TITLE
What is our focus for v0.3?

### ISSUE THREAD

**Issue by cg505** [kotct/docket-old#54]
It's been a while, and I don't quite remember. We don't have a v0.3 milestone (now fixed) and so I'm not sure what we are trying to do.

**Comment by rye** [comment]
I think we're going for having these main things:
- [ ] Multiple Docket views and the ability to move about time (#21).
  - It'd be nice if the Docket interface were cleaned up in addition to having multiple (day, week, month) views for it.
- [ ] Personal assignments (#15)
- [ ] User configuration, particularly to set defaults for various things (including #20).
- [ ] The prettiness issues in #53 need to be addressed.
  - Once I get my non-craptop back, I'll use it to make some vector art for the icons.

**Comment by rye** [comment]
I will be working soon on moving the branches around to accommodate the decisions made in #41. We should avoid using "fast-forward" merges as they do not make it obvious that a merge occurred and they can cause confusion. I've outlined this in https://github.com/kotct/docket/issues/41#issuecomment-44747403.

**Comment by cg505** [comment]
Why is do we need to know when a merge occurred if we can do a fast-forward? It seems unnecessarily complicated.

**Comment by cg505** [comment]
So do we have a succinct word or short phrase for the focus, other than "more stuff"?

**Comment by cg505** [comment]
What would be the feature branch name?

**Comment by rye** [comment]
Why do we need a feature branch? Are we not allowed to work on all of those things separately and once they're finished put them all together in one release? There are multiple individual features with their own characteristics; it is pointless to have to have one feature that is added per release.

**Comment by Sammidysam** [comment]
I agree.  We should make a separate branch for each feature.

**Comment by cg505** [comment]
How about #37?
